site_name: pysopfeu
repo_url: https://github.com/mdallaire/pysopfeu
site_url: https://mdallaire.github.io/pysopfeu
site_description: Bibliothèque pour accéder aux données de la SOPFEU publiées sur Données Québec.
site_author: Mathieu Dallaire
edit_uri: edit/main/docs/
repo_name: mdallaire/pysopfeu
copyright: Maintained by <a href="https://mdallaire.com">Florian</a>.

nav:
  - Home: index.md
  - Modules: modules.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
            - import sys
            - sys.path.append('../')
theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/mdallaire/pysopfeu
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/pysopfeu

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
